#!/bin/bash

set -e

DIRNAME=$(dirname $0)
mv $DIRNAME/ntk-host.service /etc/systemd/system
mv $DIRNAME/ntk-host /usr/bin/
chmod +x /usr/bin/ntk-host

mkdir -p /var/log/ntk
rm -f /var/log/ntk/*
touch /var/log/ntk/output.log
touch /var/log/ntk/error.log

systemctl enable --now --system ntk-host.service