[workspace]
members = [
    "src/host",
    "src/enclave",
    "src/common"
]
resolver = "3"

[workspace.dependencies]
tun = { version = "0.7.21", features = ["async"] }
nix = { version = "0.30.1", features = ["socket", "poll"] }
vsock = "0.5.1"