name: Release

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Tag for the release (e.g., 1.0.0)'
        required: true
      release_body:
        description: 'Description or changelog for the release'
        required: false

jobs:
  build-and-release:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build the project
        run: |
          make
          make release
      
      - name: Push Docker Image
        run: |
          docker tag ntk-ubuntu oraclekitio/ntk-ubuntu:${{ github.event.inputs.release_tag }}
          docker push oraclekitio/ntk-ubuntu:${{ github.event.inputs.release_tag }}

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.release_tag }}
          body: ${{ github.event.inputs.release_body }}
          prerelease: true
          files: |
            installer.sh
            build/release.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
